name: workflow overview
on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  my_self-hosted_job:
    name: my self hosted job
    runs-on: self-hosted
    steps:
      - name: step in a self-hosted runner
        id: selfHostedId
        shell: cmd
        run: |
          echo "this is a multiline"
          echo "it's running on self-hosted  runner"